;-------------------------------------------------------------------------------
; MIT License
;
; Copyright (c) 2020 Erukaron
;
; Permission is hereby granted, free of charge, to any person obtaining a copy
; of this software and associated documentation files (the "Software"), to deal
; in the Software without restriction, including without limitation the rights
; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
; copies of the Software, and to permit persons to whom the Software is
; furnished to do so, subject to the following conditions:
;
; The above copyright notice and this permission notice shall be included in all
; copies or substantial portions of the Software.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
; SOFTWARE.
;-------------------------------------------------------------------------------

;-------------------------------------------------------------------------------
; TONY function key constants
;-------------------------------------------------------------------------------

FUNC_KEY_IDENT_B            equ 0xBE
FUNC_KEY_IDENT_A            equ 0xEF

FUNC_KEY_ESC                equ 0x01
FUNC_KEY_F1                 equ 0x02
FUNC_KEY_F2                 equ 0x03
FUNC_KEY_F3                 equ 0x04
FUNC_KEY_F4                 equ 0x05
FUNC_KEY_F5                 equ 0x06
FUNC_KEY_F6                 equ 0x07
FUNC_KEY_F7                 equ 0x08
FUNC_KEY_F8                 equ 0x09
FUNC_KEY_F9                 equ 0x0a
FUNC_KEY_F10                equ 0x0b
FUNC_KEY_F11                equ 0x0c
FUNC_KEY_F12                equ 0x0d
FUNC_KEY_PRINT_SCREEN       equ 0x0e
FUNC_KEY_SCROLL_LOCK        equ 0x0f

FUNC_KEY_INSERT             equ 0x10
FUNC_KEY_DELETE             equ 0x11
FUNC_KEY_HOME               equ 0x12
FUNC_KEY_END                equ 0x13
FUNC_KEY_PAGE_UP            equ 0x14
FUNC_KEY_PAGE_DOWN          equ 0x15

FUNC_KEY_DOWN_ARROW         equ 0x20
FUNC_KEY_RIGHT_ARROW        equ 0x21
FUNC_KEY_LEFT_ARROW         equ 0x22
FUNC_KEY_UP_ARROW           equ 0x23

FUNC_KEY_CAPS_LOCK          equ 0x30
FUNC_KEY_SHIFT              equ 0x31
FUNC_KEY_SHIFT_R            equ 0x32
FUNC_KEY_ALT                equ 0x33
FUNC_KEY_ALT_GR             equ 0x34
FUNC_KEY_CTRL               equ 0x35
FUNC_KEY_CTRL_R             equ 0x36
 
FUNC_KEY_NUM_LOCK           equ 0x41

;-------------------------------------------------------------------------------